export const wasteData = [
  { amount: '0.9', fid: 'w12', title: 'Бумага' },
  { amount: '3.0', fid: 'w13', title: 'Масла' },
  { amount: '0.07', fid: 'w4', title: 'Карандаши' },
  { amount: '0.87', fid: 'w14', title: 'Масла' },
  { amount: '3.7', fid: 'w3', title: 'Щепа' },
  { amount: '12.0', fid: 'w19', title: 'Тяжелые газы' },
  { amount: '0.767', fid: 'w15', title: 'Синтетические масла' },
  { amount: '6.0', fid: 'w16', title: 'Трубы малые' },
  { amount: '0.05', fid: 'w11', title: 'Газеты' },
  { amount: '53.0', fid: 'w17', title: 'Трубы большие' },
  { amount: '1.53', fid: 'w2', title: 'Брусья' },
  { amount: '1.0', fid: 'w10', title: 'Газеты' },
  { amount: '0.31', fid: 'w9', title: 'Бумага' },
  { amount: '0.6', fid: 'w1', title: 'Щепки от сутльев' },
  { amount: '0.3', fid: 'w8', title: 'Газеты' },
  { amount: '1.0', fid: 'w5', title: 'Масла' },
  { amount: '15.0', fid: 'w6', title: 'Нефтянные масла' },
  { amount: '0.2', fid: 'w7', title: 'Нефть' },
  { amount: '4.0', fid: 'w20', title: 'Бутылки' },
  { amount: '1.7', fid: 'w24', title: 'Строительный мусор' },
  { amount: '0.67', fid: 'w22', title: 'Тара' },
  { amount: '1.5', fid: 'w21', title: 'Тара' },
  { amount: '23.0', fid: 'w23', title: 'Строительный мусор' },
  { amount: '4.0', fid: 'w25', title: 'Строительный мусор' },
  { amount: '0.78', fid: 'w26', title: 'Строительный мусор' },
  { amount: '14.0', fid: 'w27', title: 'Стужки металлические' },
  { amount: '5.0', fid: 'w28', title: 'Стужки металлические' },
  { amount: '15.0', fid: 'w30', title: 'Металл' },
  { amount: '2.0', fid: 'w29', title: 'Стужки чугунные' },
  { amount: '3.7', fid: 'w31', title: 'Металл' },
  { amount: '49.0', fid: 'w32', title: 'Металл' },
  { amount: '3.0', fid: 'w33', title: 'Металл' },
];

export const wasteTypes = [
  { fid: 'SW1', title: 'Отходы бумажных изделий' },
  { fid: 'SW10', title: 'Отходы стеклопластиковых труб' },
  { fid: 'SW2', title: 'Пластиковая тара' },
  { fid: 'SW3', title: 'Деревянные щепки' },
  { fid: 'SW4', title: 'Цветной металлалом' },
  { fid: 'SW5', title: 'Строительный мусор' },
  { fid: 'SW6', title: 'Стружка чугунная' },
  { fid: 'SW7', title: 'Нефтяные промывочные жидкости' },
  { fid: 'SW8', title: 'Отходы упакованных газов' },
  { fid: 'SW9', title: 'Отходы синтетических масел компрессорных' },
];
